# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "Getting started"
  link: "/getting-started"
- label: Usage
  items:
    - label: "Importing a dataset"
      link: "/usage/importing-a-dataset"
    - label: "Text normalization"
      link: "/usage/text-normalization"
    - label: "Sample splitting"
      link: "/usage/sample-splitting"
    - label: "Dataset cleaning"
      link: "/usage/dataset-cleaning"
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: "Github"
      link: https://github.com/dunky11/voicesmith
